- name: Creating vault user group
  group: 
    name: "{{ vault_group }}"
  become: true

- name: Creating vault user
  user:
    name: "{{ vault_user }}"
    group: "{{ vault_group }}"
    system: yes
    shell: "/sbin/nologin"
    comment: "vault nologin User"
    createhome: "no"
    state: present

# - name: Install prerequisites
#   package:
#     name: "{{ item }}"
#     update_cache: yes
#   with_items: "{{ vault_install_prerequisites }}"
#   become: yes

# - name: Download binary
#   get_url:
#     url: https://releases.hashicorp.com/vault/{{vault_version}}/vault_{{vault_version}}_linux_amd64.zip
#     dest: /tmp/vault_{{vault_version}}_linux_amd64.zip
#     owner: "{{ vault_user }}"
#     group: "{{ vault_group }}"
#     mode: 0755
#     checksum: "{{vault_checksum}}"
#   register: vault_download

# - name: "Unzip vault archive"
#   unarchive:
#     src: "{{ vault_download.dest }}"
#     dest: /usr/local/bin
#     copy: no
#     owner: "{{ vault_user }}"
#     group: "{{ vault_group }}"
#     mode: 0755

- name: Copy vault binaries to /usr/local/b
  copy:
    src: /usr/vault
    dest: /usr/local/bin

- name: "Set vault binary capabilities"
  capabilities:
    path: /usr/local/bin/vault
    capability: cap_ipc_lock+ep
    state: present

- name: Copy systemd init file
  template:
    src: init.service.j2
    dest: /etc/systemd/system/vault.service
    owner: root
    group: root
  notify: systemd_reload

- name: Creates directory
  file:
    path: /etc/vault.d
    state: directory

- name: config file
  template:
    src: vault.hcl.j2
    dest: "{{ vault_config_path }}"
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"

- name: Creates data directory
  file:
    path: /opt/data
    state: directory

- name: make dirs 0755   
  command: find {{ vault_data_path }} -type d ! -perm 0755 -exec chmod 0755 {} \;

- name: recursively update{{ vault_data_path }} directory owner
  file:
    path: "{{ vault_data_path }}"
    state: directory
    recurse: yes
    owner: vault

- name: vault service
  service:
    name: vault
    state: started
    enabled: yes
